#!/bin/sh -
##
# \file		wopr
# \brief	an improved version of the BSD-script wargames
# \author	Dietmar Muscholik <d.muscholik@t-online.de>
# \date		2021-01-25
#
# Copyright (c) 2021, Dietmar Muscholik
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#	This product includes software developed by the University of
#	California, Berkeley and its contributors.
# 4. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

game=""
echo "Welcome Dr. Falken."

while true; do
	echo -n "Would you like to play a game? "
	read x

	case $x in
	list|list\ games)
		ls /usr/games #| more
		;;
	help|help\ games)
		echo -n "Which game? "
		read x
		x=`echo $x | sed 's/[^a-z0-9]//g'`
		if [ -f /usr/share/man/man6/$x.6 ] ; then
			man $x
			#tput cl
		fi
		;;
	no|bye|logoff)
		break
		;;
	yes)
		echo -n "Which game? "
		read game
		;;
	*)
		game=$x
		;;
	esac

	if [ -n "$game" ] ; then
		game=`echo $game | sed 's/[^a-z0-9]//g'`
		if [ -x /usr/games/$game ] ; then
			tput cl
			/usr/games/$game
		else
			game=""
		fi
		break
	fi
done

if [ -z "$game" ] ; then
	echo "Connection terminated."
	exit 0
fi

cat <<QUOTE
A strange game.
The only winning move is
not to play.
QUOTE
exit 0

